export const trackMetadataTitleClass = 'min-w-0 flex-1 overflow-hidden'
export const trackMetadataArtistClass = 'min-w-0 flex-1 truncate'
export const trackMetadataArtistInlineClass = 'min-w-0 shrink truncate'
export const trackMetadataLoadingClass = 'min-w-0 max-w-[120px] shrink truncate'
export const trackMetadataProgressClass = 'w-full max-w-[560px] min-w-[320px]'
