export const trackMetadataTitleClass = 'min-w-0 flex-1 overflow-hidden'
export const trackMetadataArtistClass = 'min-w-0 flex-1 truncate'
export const trackMetadataArtistInlineClass = 'min-w-0 shrink truncate'
export const trackMetadataLoadingClass = 'min-w-0 max-w-[120px] shrink truncate'
export const trackMetadataLoopScrubberClass = 'w-[170px] shrink-0 min-w-0'
